[package]
name = "twobpp"
version = "0.1.0"
authors = ["Amy Colford <amy.colford@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
license-file = "LICENSE"
description = "A gameboy 2bpp encoder"
repository = "https://github.com/NurbsOtter/twobpp"

[dependencies]
num = "0.2.0"
